## Prior and Posterior

### Prior

$$P(C) = 0.01$$

$$\sum_i x_i$$

---

## Simulating a Coin Flip in Python

In [2]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [11]:
# outcome of one coin flip
np.random.randint(2)

1

In [4]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([0, 1, 1, ..., 1, 1, 0])

In [5]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5013

In [6]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [7]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 0, 1, ..., 1, 0, 1])

In [8]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.5068

In [9]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.204

---

## Coin Flips and Die Rolls

In [13]:
# import numpy
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

### 1. Two fair coin flips produce exactly two heads

In [15]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250321

### 2. Three fair coin flips produce exactly one head

In [18]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.374807

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [19]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.288199

### 4. A die rolls an even number

In [24]:
np.arange(2, 6),

(array([2, 3, 4, 5]),)

In [20]:
# simulate 1 million tests of one die roll
tests = np.random.choice(np.arange(1, 7), size=int(1e6))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.499411

### 5. Two dice roll a double

In [21]:
# simulate the first million die rolls
first = np.random.choice(np.arange(6), size=int(1e6))

# simulate the second million die rolls
second = np.random.choice(np.arange(6), size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.166267